version: '3'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,logs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-./docker/localstack/tmp/localstack}:/tmp/localstack"
      - "./docker/localstack/tmp/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - shared_network
  
  # awscli
  storage_init:
    image: xueshanf/awscli
    environment:
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_DEFAULT_OUTPUT=json
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      - localstack
    volumes:
      - ./build/storage_init:/root
    networks:
      - editor_network
    entrypoint: /root/wait-for-it.sh localstack:4566 -- /root/storage_init.sh
    networks:
      - shared_network
  
networks:
  shared_network:
    external: true
    
    